[plugins]
krew = "https://github.com/soupglasses/mise-krew.git#2.0.0"

# File synced from https://github.com/FasterSpeeding/Aurora-Fauxy
# Changes will not be persisted
[tools]
# Languages
go = "1.26.1"
python = "3"
rust = { version = "1.94.1", components = "rustc,cargo" }
# CLI tools
cargo-binstall = "1.15.6"
chezmoi = "2.70.1"
flux2 = "2.8.3"
git-lfs = "3.7.0"
"go:github.com/schollz/croc/v10" = "v10.4.2"
helm = "4.1.3"
"krew:tree" = "0.6.0"
# "krew:neat" = "2.0.4"
kubeconform = "0.7.0"
kustomize = "5.8.1"
uv = "0.11.3"
just = "1.49.0"
kubeseal = "0.36.0"
minikube = "1.38.1"
opentofu = "1.11.6"
"pipx:kseal" = "2.0.2"
"pipx:yt-dlp" = "2026.3.17"

[settings]
activate_aggressive = true
experimental = true
gpg_verify = true
lockfile = false
not_found_auto_install = false
paranoid = true
plugin_autoupdate_last_check_duration = "0"
go_skip_checksum = true

[settings.python]
compile = false
