[plugins]
krew = "https://github.com/soupglasses/mise-krew.git#2.0.0"

# File synced from https://github.com/FasterSpeeding/Aurora-Fauxy
# Changes will not be persisted
[tools]
# Languages
go = "1.26.5"
python = "3"
rust = { version = "1.98.1", components = "rustc,cargo" }
# CLI tools
cargo-binstall = "1.22.0"
chezmoi = "2.71.0"
claude = "2.1.251"
flux2 = "2.9.4"
git-lfs = "3.7.1"
"go:github.com/schollz/croc/v10" = "v10.7.0"
helm = "4.2.3"
just = "1.58.0"
"krew:tree" = "0.6.0"
# "krew:neat" = "2.0.4"
kubeconform = "0.8.0"
kubectl = "1.37.0"
kustomize = "5.8.1"
k9s = "0.59.0"
kubeseal = "0.39.1"
minikube = "1.38.1"
opentofu = "1.12.6"
"pipx:kseal" = "2.1.1"
tmux = "3.7c"
uv = "0.12.7"
"pipx:yt-dlp" = "2026.6.9"

[settings]
activate_aggressive = true
experimental = true
gpg_verify = true
lockfile = false
not_found_auto_install = false
paranoid = true
plugin_autoupdate_last_check_duration = "0"
go_skip_checksum = true

[settings.python]
compile = false
