[tool.piped]
default_sessions = ["verify-markup", "spell-check"]
top_level_targets = []

[tool.piped.github_actions.docker-publish]
[tool.piped.github_actions.freeze_for_pr]
[tool.piped.github_actions.resync_piped]
[tool.piped.github_actions.update_licence]
[tool.piped.github_actions.upgrade_locks]
