[tools]
# Core
go = "1.25"
python = "3"
rust = { version = "1.89", components = "rustc,cargo" }
# Plugins
uv = "0.8"
"go:github.com/schollz/croc/v10" = "v10.2.2"

[settings]
activate_aggressive = true
experimental = true
gpg_verify = true
lockfile = true
not_found_auto_install = false
paranoid = true
#plugin_autoupdate_last_check_duration = "0"
go_skip_checksum = true

[settings.python]
compile = false
uv_venv_auto = true
